"""add phone number for profiles

Revision ID: 5a4bad289d03
Revises: 116d2d074936
Create Date: 2026-02-28 12:04:22.434316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a4bad289d03'
down_revision: Union[str, None] = '116d2d074936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'phone_number')
    # ### end Alembic commands ###
