"""add is_shadowbanned

Revision ID: 8a4d5cff6310
Revises: 5a4bad289d03
Create Date: 2026-02-28 15:53:14.614159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a4d5cff6310'
down_revision: Union[str, None] = '5a4bad289d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_shadowbanned', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_shadowbanned = FALSE WHERE is_shadowbanned IS NULL")
    op.alter_column('users', 'is_shadowbanned', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_shadowbanned')
    # ### end Alembic commands ###
